---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=8010
    volumes:
      - /opt/docker/qbittorrent/config:/config
      - /hdd/Downloads:/downloads
      - /hdd/Movies:/movies
    ports:
      - 8010:8010
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped