services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    network_mode: host
    environment:
      - ROCKET_PORT=8083
      - DISABLE_ADMIN_TOKEN=false
    volumes:
      - ./vw-data/:/data/
