---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=8084
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /home/vencel/downloads:/downloads
    network_mode: host
    restart: unless-stopped
